### ISSUE TITLE
메인 페이지 구현

### ISSUE THREAD

**Issue by leey00nsu** [leey00nsu/SYU-2023-CLUBFEST-FE#2]
### 목적
메인 페이지 구현

### TODO
- [x] Header Logo 구현
- [x] 동아리 소개 구현
- [x] 동아리제 타임테이블 구현
- [x] About 구현
- [x] Footer 구현
